#**************
#**
#** Demonstrates the basic functionality of this example
#**
#**************

/run/verbose 1
/control/verbose 1
/tracking/verbose 0
/process/optical/verbose 1
/run/initialize

#/random/setSeeds 1706221035042 1706222552143

/gps/verbose 0

/gps/particle neutron
#position
/gps/pos/type Point
/gps/pos/centre 0 0 0 cm
#Angle
/gps/ang/type iso

# Energy(default)
#/gps/ene/mono 1000 keV

/gps/ene/type Arb
/gps/hist/type arb


/gps/hist/point 0 0
/gps/hist/point 0.1 0.106535
/gps/hist/point 0.3 0.165372
/gps/hist/point 0.5 0.193786
/gps/hist/point 0.7 0.207217
/gps/hist/point 0.9 0.216517
/gps/hist/point 1.1 0.237171
/gps/hist/point 1.3 0.241694
/gps/hist/point 1.5 0.232104
/gps/hist/point 1.7 0.233916
/gps/hist/point 1.9 0.24978
/gps/hist/point 2.1 0.285056
/gps/hist/point 2.3 0.26428
/gps/hist/point 2.5 0.222225
/gps/hist/point 2.7 0.215461
/gps/hist/point 2.9 0.233042
/gps/hist/point 3.1 0.289424
/gps/hist/point 3.3 0.236013
/gps/hist/point 3.5 0.173069
/gps/hist/point 3.7 0.163232
/gps/hist/point 3.9 0.18604
/gps/hist/point 4.1 0.199017
/gps/hist/point 4.3 0.111738
/gps/hist/point 4.5 0.0719
/gps/hist/point 4.7 0.0499
/gps/hist/point 4.9 0.0348
/gps/hist/point 5.1 0.0245
/gps/hist/point 5.3 0.0183
/gps/hist/point 5.5 0.0146
/gps/hist/point 5.7 0.0126
/gps/hist/point 5.9 0.0115
/gps/hist/point 6.1 0.011
/gps/hist/point 6.3 0.0107
/gps/hist/point 6.5 0.0102
/gps/hist/point 6.7 0.00887
/gps/hist/point 6.9 0.00743
/gps/hist/point 7.1 0.00714
/gps/hist/point 7.3 0.00697
/gps/hist/point 7.5 0.00589
/gps/hist/point 7.7 0.00404
/gps/hist/point 7.9 0.00264

#
# Linear interpolation between the data points is required to obtain
# the smooth energy spectrum
/gps/hist/inter Lin

/run/printProgress 10

#/vis/disable
#/random/setSavingFlag true
#/LXe/saveThreshold 1400
#/LXe/pmtThreshold 4
#/LXe/forceDrawNoPhotons true
#/run/beamOn 200

#/vis/enable
#/LXe/eventVerbose 1
#/process/optical/scintillation/setTrackSecondariesFirst false
#/run/beamOn 5
#

#/tracking/verbose 1
#/LXe/forceDrawPhotons true
#/LXe/detector/MainScintYield 100
#/process/optical/scintillation/setTrackSecondariesFirst true
#/run/beamOn 1

#/vis/enable
/vis/disable
/random/setSavingFlag false
/LXe/saveThreshold 1400
/LXe/pmtThreshold 4
#/LXe/forceDrawPhotons true
/LXe/forceDrawNoPhotons true

/analysis/setFileName LXe
/analysis/h1/set 3 100 0 10000
/analysis/h1/set 4 100 0 100
/analysis/h1/set 5 100 0 10000

#/run/beamOn 1000000

/run/beamOn 200000



